package managers.gui;

public enum GUIActionType {

    CLOSE, REDIRECT, ADD_ITEM, SET_ITEM, SET_ITEM_META, MOVE_ITEM_SWAP, MOVE_ITEM_OVERWRITE, CLOSE_FOR_ALL_PLAYERS, KILL_PLAYER, PLAY_SOUND_FOR_PLAYER, PLAY_NOTE_FOR_PLAYER, UPDATE_GUI_FOR_CLIENT, SEND_MESSAGE, SEND_TEXT_COMPONENT, EXECUTE_SQL_UPDATE_STATEMENT, EXECUTE_SQL_QUERY_STATEMENT, EXECUTE_FUNCTION;
    
}
